power <- read.table("c:/TTforR/household_power_consumption.txt",skip=1,sep=";")
names(power) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
View(power)
subpower <- subset(power,power$Date=="1/2/2007" | power$Date =="2/2/2007")
View(subpower)
hist(as.numeric(as.character(subpower$Global_active_power)),col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
title(main="Global Active Power")
dev.copy(png, "plot1.png")
dev.off()
savehistory("C:/TTforR/project1/plot1.R")
